
import java.awt.Graphics;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class Paparde extends javax.swing.JFrame {
    double[][] punkti = new double[1][2];
    
    double[][] reiz1 =   {{0.0,0.0}, {0.0,0.16}};
    double[][] reiz2 =   {{0.85,0.04}, {-0.04,0.85}};
    double[][] reiz3 =   {{0.2,-0.26}, {0.23,0.22}};
    double[][] reiz4 =   {{-0.15,0.28}, {0.26,0.24}};
    double[] p1 = {0,1.6};
    double[] p2 = {0,0.44};
    /**
     * Creates new form Paparde
     */
    public Paparde() {
        initComponents();
        //punkti[0][1] = 0;
        //punkti[0][0] = 2;
        spin.setValue(9000);
    }
    
    void reizina(double[][] reiz){
        double[][] p = new double[1][2];
        for(int i =0; i< punkti.length;i++){
            for(int j=0;j<punkti[0].length;j++){
                p[i][j] = punkti[i][j];
            }
        }
        for(int i =0; i<p.length;i++){
            for(int j =0; j<reiz[0].length;j++){
                punkti[i][j] = 0;
                for(int k=0;k<p[0].length;k++){
                    //System.out.println(p[i][k]);
                    //System.out.println(reiz[k][j]);
                    punkti[i][j]+=p[i][k]*reiz[k][j];
                    //System.out.println(punkti[i][j]);
                    
                }
                //System.out.println("i "+i);
                //System.out.println("j "+j);
                //System.out.println("value "+punkti[i][j]);
            }
        }
    }
    void pieskaitit(double[] p){
        for(int i=0;i<punkti.length;i++){
            for(int j =0;j<punkti[0].length;j++){
                punkti[i][j] += p[j];
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zimet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spin = new javax.swing.JSpinner();
        panelis = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        zimet.setText("Zimet");
        zimet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zimetActionPerformed(evt);
            }
        });

        jLabel1.setText("CIk zimet?");

        panelis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelisLayout = new javax.swing.GroupLayout(panelis);
        panelis.setLayout(panelisLayout);
        panelisLayout.setHorizontalGroup(
            panelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        panelisLayout.setVerticalGroup(
            panelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 143, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zimet)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zimet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zimetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zimetActionPerformed
        //reizina();
        /*int n = 900000;
        Graphics g= panelis.getGraphics();
        Random rand=new Random();
        for(int i=0;i<n;i++){
        g.drawRect((punkti[0][0]),(punkti[0][1]),2,2);
        //g.drawRect(punkti[0][0]+200, i, i, i);
        int p=rand.nextInt(3);
        if (p==0) reizina();
        else if (p==1){reizina();pieskaitit(p1);}
        else {reizina();pieskaitit(p2);}
        }*/
        Graphics g= panelis.getGraphics();
        g.clearRect(0, 0, panelis.getWidth(), panelis.getHeight());
        Random rand=new Random();
        for(int i=0;i<(int)spin.getValue();i++){
        //g.fillRect((int)((punkti[0][0]+2.5)*20),(int)((punkti[0][1])*20),1,1);
        g.fillRect((int)(panelis.getWidth()/2+punkti[0][0]*panelis.getWidth()/11), (int)(panelis.getHeight()-punkti[0][1]*panelis.getHeight()/11), 1, 1);
        //g.drawRect(punkti[0][0]+200, i, i, i);
        int p=rand.nextInt(100)+1;
        if (p==1){reizina(reiz1);}
        else if (p>=2 && p<=86){reizina(reiz2);pieskaitit(p1);}
        else if (p>=87 && p<=93){reizina(reiz3);pieskaitit(p1);}
        else{reizina(reiz4);pieskaitit(p2);};
        }
    }//GEN-LAST:event_zimetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paparde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paparde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paparde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paparde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paparde().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelis;
    private javax.swing.JSpinner spin;
    private javax.swing.JButton zimet;
    // End of variables declaration//GEN-END:variables
}
